services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"  
    # env_file:
    #   - .env
    volumes:
      - .:/app
    command: streamlit run app/main.py --server.port=8501 --server.address=0.0.0.0